services:
  # Combined TTS + Physics Book Server (now with Azure DeepSeek-V3)
  chatterbox-combined:
    build: 
      context: .
      dockerfile: Dockerfile.voices
    ports:
      - "5001:5001"  # TTS server
      - "5000:5000"  # Physics book server
    volumes:
      - "./voices:/app/voices:ro"
      - "./audio_outputs:/app/audio_outputs"  # Mount audio outputs for easy access
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health", "&&", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s